---
title: "GG618"
output: html_document
date: "2023-03-31"
---
```{r,echo=FALSE, message=FALSE,warning = FALSE, error = FALSE, results='hide'}
#####reading packages
local({r <- getOption("repos")
       r["CRAN"] <- "http://cran.r-project.org" 
       options(repos=r)})

if(!require("tidyverse"))install.packages("tidyverse")
if(!require("dplyr"))install.packages('dplyr')
if(!require("openair"))install.packages('openair')
if(!require("viridis"))install.packages('viridis')
if(!require("here"))install.packages('here')
if(!require("Directional"))install.packages('Directional')
if(!require("bpnreg"))install.packages('bpnreg')
if(!require("circular"))install.packages('circular')
if(!require("ggplot2"))install.packages('ggplot2')
if(!require("windrose"))install.packages('windrose')
if(!require("clifro"))install.packages('clifro')
if(!require("geomtextpath"))install.packages('geomtextpath')
if(!require("glue"))install.packages('glue')
if(!require("scales"))install.packages('scales')

library(scales)
library(glue)
library(geomtextpath)
library(tidyverse)
library(dplyr)
library(openair)
library(viridis)
library(here)
library(Directional)
library(bpnreg)
library(circular)
library(ggplot2)
require(windrose)
library(clifro)
```


### Circular Mean
```{r,echo=FALSE, message=FALSE,warning = FALSE, error = FALSE, results='hide'}
wind<-wind %>%group_by(month(datetime)) %>%
  mutate(
    n=n(),
  c_sin=sum(sin(winddir*(pi/180))), 
  c_cos=sum(cos(winddir*(pi/180))),
  circular=(atan(c_sin/c_cos))/pi,
  c_dir=ifelse(c_sin>=0,
                      ifelse(c_cos>=0,atan(c_sin/c_cos)/pi*180,180+atan(c_sin/c_cos)/pi*180),
                      ifelse(c_cos>=0,360+atan(c_sin/c_cos)/pi*180,180+atan(c_sin/c_cos)/pi*180)),
  c_r =sqrt((c_sin^2+c_cos^2))/n,
c_variance = 1-(sqrt((c_sin^2+c_cos^2))/n))

# weighted by wind direction
wind2<-wind %>%group_by(month(datetime)) %>%
  mutate( 
    w_sin=sum(windspeed*sin(winddir*(pi/180))), 
    w_cos=sum(windspeed*cos(winddir*(pi/180))),
    w_circular=(atan(w_sin/w_cos))/3.1415926180,
    w_dir=ifelse(w_sin>=0,
                      ifelse(w_cos>=0,atan(w_sin/w_cos)/pi*180,180+atan(w_sin/w_cos)/pi*180),
                      ifelse(w_cos>=0,360+atan(w_sin/w_cos)/pi*180,180+atan(w_sin/w_cos)/pi*180)),
    w_r = sqrt((w_sin^2+w_cos^2))/sum(windspeed),
    w_variance = 1-(sqrt((w_sin^2+w_cos^2))/sum(windspeed)))

wind3 <- wind2 %>% ungroup() %>% 
  select(month, 
         windspeed,
         winddir, 
         c_dir, 
         w_dir, 
         mean_speed,
         c_r, c_variance, w_r, w_variance)
library(scales)
wind3 <- wind3 %>% mutate(
  s_c_dir = rescale(c_dir),
  s_winddir = rescale(winddir),
  s_mean_speed = rescale(mean_speed)
)


k_1<- kmeans(wind3%>% filter(month==1)%>% select(s_winddir,s_mean_speed), centers = 2) 
k_2<- kmeans(wind3%>% filter(month==2)%>% select(s_winddir,s_mean_speed), centers = 2)
k_3<- kmeans(wind3%>% filter(month==3)%>% select(s_winddir,s_mean_speed), centers = 2) 
k_4<- kmeans(wind3%>% filter(month==4)%>% select(s_winddir,s_mean_speed), centers = 2) 
k_5<- kmeans(wind3%>% filter(month==5)%>% select(s_winddir,s_mean_speed), centers = 2)
k_6<- kmeans(wind3%>% filter(month==6)%>% select(s_winddir,s_mean_speed), centers = 2)
k_7<- kmeans(wind3%>% filter(month==7)%>% select(s_winddir,s_mean_speed), centers = 2)
k_8<- kmeans(wind3%>% filter(month==8)%>% select(s_winddir,s_mean_speed), centers = 2)
k_9<- kmeans(wind3%>% filter(month==9)%>% select(s_winddir,s_mean_speed), centers = 2)
k_10<- kmeans(wind3%>% filter(month==10)%>% select(s_winddir,s_mean_speed), centers = 2)
k_11<- kmeans(wind3%>% filter(month==11)%>% select(s_winddir,s_mean_speed), centers = 2)
k_12<- kmeans(wind3%>% filter(month==12)%>% select(s_winddir,s_mean_speed), centers = 2)

a2<-wind3%>% filter(month==2)%>%mutate(
    cluster = k_2$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 3, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Feb 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#Jan
a1<- wind3%>% filter(month==1)%>%mutate(
    cluster = k_1$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Jan 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")

```

```{R}
#Jan
a1<-wind3%>% filter(month==1)%>%mutate(
    cluster = k_1$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 3, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Jan 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")

```

```{r}
#Mar
a3<-wind3%>% filter(month==3)%>%mutate(
    cluster = k_3$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 3, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Mar 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")

```

```{r}
#Apr
a4<-wind3%>% filter(month==4)%>%mutate(
    cluster = k_4$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir-15, y = 2, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Apr 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#May
a5<-wind3%>% filter(month==5)%>%mutate(
    cluster = k_5$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 3, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in May 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#Jun
a6<-wind3%>% filter(month==6)%>%mutate(
    cluster = k_6$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir-20, y = 3, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Jun 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#Jul
a7<-wind3%>% filter(month==7)%>%mutate(
    cluster = k_7$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir+15, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Jul 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#Aug
a8<-wind3%>% filter(month==8)%>%mutate(
    cluster = k_8$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Aug 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```

```{r}
#Sep
a9<-wind3%>% filter(month==9)%>%mutate(
    cluster = k_9$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Sep 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```


```{r}
#Oct
a10<-wind3%>% filter(month==10)%>%mutate(
    cluster = k_10$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Oct 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```


```{r}
#Nov
a11<-wind3%>% filter(month==11)%>%mutate(
    cluster = k_11$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Nov 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")
```


```{r}
#Dec
a12<-wind3%>% filter(month==12)%>%mutate(
    cluster = k_12$cluster%>%as.factor())%>% ggplot(aes(x = winddir, y = windspeed))+
  geom_point(aes(color = cluster), alpha = 0.5)+
  theme_classic()+scale_color_manual(values = c("darkblue", "darkorange"))+
  geom_segment(aes(x=w_dir, y=0, xend=w_dir, yend=mean_speed), 
               linewidth =2,
               arrow = arrow(length=unit(20, 'pt')), color = "red")+
  geom_text(aes(x=w_dir, y = 1, 
                label = glue("Prevailing Wind Dir:{round(w_dir,2)}
                             \nWind Speed:{round(mean_speed,2)}")), size = 3)+
  labs(x ="Wind Direction",
    y = "Wind Speed",
    title = "Cluster of Wind in Dec 2022"
  )+scale_x_continuous(breaks = seq(0, 360, by =22.5),
                       labels = c("E","22.5","NE","67.5",
                                  "N","112.5","NW","157.5","W",
                                  "202.5","SW","247.5","S","292.5",
                                  "SE","337.5","E"))+
  theme(
    plot.title = element_text(face ="bold", hjust =0.5),legend.position ="none")



```

```{r}
library(patchwork)


a1|a2|a3|a4
ggsave("distribution1.png", width = 50, height = 10, units =c("cm"))
a5|a6|a7|a8
ggsave("distribution2.png", width = 50, height = 10, units =c("cm"))
a9|a10|a11|a12
ggsave("distribution3.png", width = 50, height = 10, units =c("cm"))
```

